/**
 * Authentication types module
 *
 * @module api/auth/auth-types
 */

/**
 * Authentication-related TypeScript types
 *
 * Re-exports types from the generated API schemas for cleaner imports.
 * These types are automatically generated by Orval from the OpenAPI specification.
 */
export type { LoginRequest, UserDto } from '../__generated__/api.schemas';
