/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pannonwork Admission Task Backend
 * OpenAPI spec version: v1
 */
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import * as axios from 'axios';

import type {
  CreateUserRequest,
  GetApiUsersParams,
  UserDto,
  UserDtoPagination,
} from '../api.schemas';

export const getUser = () => {
  /**
   * @summary Get the user with the given id
   */
  const getApiUsersId = <TData = AxiosResponse<UserDto>>(
    id: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`/api/users/${id}`, options);
  };
  /**
   * @summary Update a user
   */
  const putApiUsersId = <TData = AxiosResponse<UserDto>>(
    id: number,
    createUserRequest: CreateUserRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.put(`/api/users/${id}`, createUserRequest, options);
  };
  /**
   * @summary Delete a user
   */
  const deleteApiUsersId = <TData = AxiosResponse<UserDto>>(
    id: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.delete(`/api/users/${id}`, options);
  };
  /**
   * @summary Get all users
   */
  const getApiUsers = <TData = AxiosResponse<UserDtoPagination>>(
    params?: GetApiUsersParams,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`/api/users`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Create a user
   */
  const postApiUsers = <TData = AxiosResponse<UserDto>>(
    createUserRequest: CreateUserRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.post(`/api/users`, createUserRequest, options);
  };
  return {
    getApiUsersId,
    putApiUsersId,
    deleteApiUsersId,
    getApiUsers,
    postApiUsers,
  };
};
export type GetApiUsersIdResult = AxiosResponse<UserDto>;
export type PutApiUsersIdResult = AxiosResponse<UserDto>;
export type DeleteApiUsersIdResult = AxiosResponse<UserDto>;
export type GetApiUsersResult = AxiosResponse<UserDtoPagination>;
export type PostApiUsersResult = AxiosResponse<UserDto>;
