/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pannonwork Admission Task Backend
 * OpenAPI spec version: v1
 */
export interface CreateEmployeeRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  placeOfBirth?: string | null;
  /** @nullable */
  mothersFirstName?: string | null;
  /** @nullable */
  mothersLastName?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  zipCode?: string | null;
  /** @nullable */
  parcelNumber?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  administrativeArea?: string | null;
  /** @nullable */
  administrativeAreaType?: string | null;
  /** @nullable */
  houseNumber?: string | null;
  /** @nullable */
  building?: string | null;
  /** @nullable */
  staircase?: string | null;
  /** @nullable */
  floor?: string | null;
  /** @nullable */
  door?: string | null;
  /** @nullable */
  phone?: string | null;
  sex?: Sex;
  education?: Education;
  paymentMethod?: PaymentMethod;
  /** @nullable */
  bankAccountNumber?: string | null;
  /** @nullable */
  moneyDispatchAddress?: string | null;
  /** @nullable */
  cashPaymentDay?: number | null;
  /** @nullable */
  salary?: number | null;
}

export interface CreateUserRequest {
  /** @nullable */
  password?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  group?: UserGroup;
}

export type Education = (typeof Education)[keyof typeof Education];

export const Education = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
} as const;

export interface EmployeeDto {
  id?: number;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  placeOfBirth?: string | null;
  /** @nullable */
  mothersFirstName?: string | null;
  /** @nullable */
  mothersLastName?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  zipCode?: string | null;
  /** @nullable */
  parcelNumber?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  administrativeArea?: string | null;
  /** @nullable */
  administrativeAreaType?: string | null;
  /** @nullable */
  houseNumber?: string | null;
  /** @nullable */
  building?: string | null;
  /** @nullable */
  staircase?: string | null;
  /** @nullable */
  floor?: string | null;
  /** @nullable */
  door?: string | null;
  /** @nullable */
  phone?: string | null;
  sex?: Sex;
  education?: Education;
  paymentMethod?: PaymentMethod;
  /** @nullable */
  bankAccountNumber?: string | null;
  /** @nullable */
  moneyDispatchAddress?: string | null;
  /** @nullable */
  cashPaymentDay?: number | null;
  /** @nullable */
  salary?: number | null;
}

export interface EmployeeDtoPagination {
  /** @nullable */
  data?: EmployeeDto[] | null;
  total?: number;
}

export interface LoginRequest {
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
}

/**
 * @nullable
 */
export type ObjectAppErrorErrorObject = unknown | null;

export interface ObjectAppError {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  detailedMessage?: string | null;
  /** @nullable */
  errorObject?: ObjectAppErrorErrorObject;
}

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod];

export const PaymentMethod = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export type Sex = (typeof Sex)[keyof typeof Sex];

export const Sex = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface UserDto {
  id?: number;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  group?: UserGroup;
  /** @nullable */
  lastActive?: string | null;
  created?: string;
}

export interface UserDtoPagination {
  /** @nullable */
  data?: UserDto[] | null;
  total?: number;
}

export type UserGroup = (typeof UserGroup)[keyof typeof UserGroup];

export const UserGroup = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;

export type GetApiEmployeesParams = {
  Search?: string;
  OrderBy?: string;
  Limit?: number;
  Offset?: number;
};

export type GetApiUsersParams = {
  Search?: string;
  OrderBy?: string;
  Limit?: number;
  Offset?: number;
};
