/**
 * Employee types module
 *
 * @module api/employees/employee-types
 */

/**
 * Employee-related TypeScript types
 *
 * Re-exports types from the generated API schemas for cleaner imports.
 * These types are automatically generated by Orval from the OpenAPI specification.
 */
export type {
  CreateEmployeeRequest,
  EmployeeDto,
  EmployeeDtoPagination,
  GetApiEmployeesParams,
} from '../__generated__/api.schemas';
