/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pannonwork Admission Task Backend
 * OpenAPI spec version: v1
 */
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import * as axios from 'axios';

import type { LoginRequest, UserDto } from '../api.schemas';

export const getAuthentication = () => {
  /**
   * @summary Returns the current user
   */
  const getApiAuthMe = <TData = AxiosResponse<UserDto[]>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`/api/auth/me`, options);
  };
  /**
   * @summary Sends a login request
   */
  const postApiAuthLogin = <TData = AxiosResponse<UserDto[]>>(
    loginRequest: LoginRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.post(`/api/auth/login`, loginRequest, options);
  };
  /**
   * @summary Sends a logout request
   */
  const postApiAuthLogout = <TData = AxiosResponse<UserDto[]>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.post(`/api/auth/logout`, undefined, options);
  };
  return { getApiAuthMe, postApiAuthLogin, postApiAuthLogout };
};
export type GetApiAuthMeResult = AxiosResponse<UserDto[]>;
export type PostApiAuthLoginResult = AxiosResponse<UserDto[]>;
export type PostApiAuthLogoutResult = AxiosResponse<UserDto[]>;
