/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pannonwork Admission Task Backend
 * OpenAPI spec version: v1
 */
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import * as axios from 'axios';

import type {
  CreateEmployeeRequest,
  EmployeeDto,
  EmployeeDtoPagination,
  GetApiEmployeesParams,
} from '../api.schemas';

export const getEmployee = () => {
  /**
   * @summary Get the employee with the given id
   */
  const getApiEmployeesId = <TData = AxiosResponse<EmployeeDto>>(
    id: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`/api/employees/${id}`, options);
  };
  /**
   * @summary Update an employee
   */
  const putApiEmployeesId = <TData = AxiosResponse<EmployeeDto>>(
    id: number,
    createEmployeeRequest: CreateEmployeeRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.put(
      `/api/employees/${id}`,
      createEmployeeRequest,
      options
    );
  };
  /**
   * @summary Delete an employee
   */
  const deleteApiEmployeesId = <TData = AxiosResponse<EmployeeDto>>(
    id: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.delete(`/api/employees/${id}`, options);
  };
  /**
   * @summary Get all employees
   */
  const getApiEmployees = <TData = AxiosResponse<EmployeeDtoPagination>>(
    params?: GetApiEmployeesParams,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`/api/employees`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Create an employee
   */
  const postApiEmployees = <TData = AxiosResponse<EmployeeDto>>(
    createEmployeeRequest: CreateEmployeeRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.post(`/api/employees`, createEmployeeRequest, options);
  };
  return {
    getApiEmployeesId,
    putApiEmployeesId,
    deleteApiEmployeesId,
    getApiEmployees,
    postApiEmployees,
  };
};
export type GetApiEmployeesIdResult = AxiosResponse<EmployeeDto>;
export type PutApiEmployeesIdResult = AxiosResponse<EmployeeDto>;
export type DeleteApiEmployeesIdResult = AxiosResponse<EmployeeDto>;
export type GetApiEmployeesResult = AxiosResponse<EmployeeDtoPagination>;
export type PostApiEmployeesResult = AxiosResponse<EmployeeDto>;
