name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
      - 'typedoc.json'
      - '.github/workflows/docs.yml'
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # Step 1: Get the code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Bun runtime (package manager)
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Generate TypeDoc documentation from code
      - name: Generate TypeDoc documentation
        run: bun run docs:generate --skipErrorChecking

      # Step 5: Disable Jekyll processing for static HTML files
      # This is critical - without this, GitHub Pages tries to process our TypeDoc HTML as Jekyll
      - name: Disable Jekyll processing
        run: |
          mkdir -p docs
          echo '' > docs/.nojekyll
          echo '✓ Created .nojekyll file to disable Jekyll processing'

      # Step 6: Configure GitHub Pages deployment
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      # Step 7: Upload the generated docs folder as artifact
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
